language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
global:
  - PINS=cow.0.2.0:https://github.com/samoht/ocaml-cow.git
env:
  - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02
